name: Build userscript

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install build deps
        working-directory: build
        run: npm install

      - name: Run build
        working-directory: build
        run: npm run build

      - name: Commit built file
        run: |
          if [ -n "$(git status --porcelain prod/)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add prod/pmd-plus.user.js
            git commit -m "chore: build userscript (CI) [skip ci]"
            git push
          else
            echo "Nothing to commit."
          fi
